# Generated by Django 4.1.5 on 2023-03-17 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_user_following_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
