# Generated by Django 4.1.5 on 2023-03-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_follow_user_follow_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
