# Generated by Django 4.1.5 on 2023-03-20 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
