# Generated by Django 4.1.5 on 2023-03-20 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_followed_users_user_following_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='user',
            name='follower_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
