# Generated by Django 4.1.5 on 2023-03-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
